const $=id=>document.getElementById(id);let analysis=null;
const esc=value=>String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const toast=text=>{$("toast").textContent=text;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)};
async function api(url,options){const response=await fetch(url,options);if(!response.ok)throw new Error(await response.text());return response.json()}
function summaryCard(label,value){return `<div class="summary-card"><span>${label}</span><strong>${Number(value||0).toLocaleString()}</strong></div>`}
function renderProjects(items){const cards=$("projectCards");$("projectCount").textContent=`${items.length} 个项目`;let boards=0,completed=0;items.forEach(item=>{boards+=Number(item.plate_count||0);completed+=Number(item.completed_plate_count||0)});$("summaryCards").innerHTML=[summaryCard("项目",items.length),summaryCard("板子",boards),summaryCard("已完成板子",completed),summaryCard("待处理板子",Math.max(0,boards-completed))].join("");cards.innerHTML=items.length?items.map(item=>`<article class="project-card" data-url="${esc(item.detail_url)}"><h3>${esc(item.project_name)}</h3><p class="path">${esc(item.root||"未记录数据根目录")}</p><div class="project-meta"><span class="pill">${item.plate_count||0} 块板</span><span class="pill">${item.completed_plate_count||0} 块已完成</span></div><span class="open">打开项目 →</span></article>`).join(""):`<div class="empty">暂无项目，请新建任务。</div>`;cards.querySelectorAll("[data-url]").forEach(card=>card.addEventListener("click",()=>{window.location.href=card.dataset.url}))}
async function load(){try{renderProjects(await api("/api/projects"));await loadTasks()}catch(error){toast(`加载失败：${error.message}`)}}
async function loadTasks(){const tasks=await api("/api/project/tasks");$("taskRows").innerHTML=tasks.length?tasks.slice().reverse().map(task=>`<div class="task"><strong>${esc(task.name)}</strong><span>${esc(task.path)}</span><span class="status ${esc(task.status)}">${esc(task.status)}</span><small>${task.group_count||0} 组 · 已选 ${esc((task.selected_timepoint_labels||[]).join(", "))} · 末点 ${esc(task.endpoint_day_label||"—")}</small></div>`).join(""):`<div class="empty">暂无任务</div>`}
function renderAnalysis(value){analysis=value;const options=value.timepoint_options||[];$("analysisResult").textContent=`已解析：${value.group_count} 个板组，${value.session_count} 个时间点文件夹\n实际日龄：${(value.day_labels||[]).join(", ")}\n完整96孔组：${value.complete_groups}`;const picker=$("timepointPicker");picker.hidden=false;const defaults=new Set(value.default_selected_timepoint_labels||[]);picker.innerHTML=options.map(item=>{const day=item.day_label;const required=item.required_early;const checked=defaults.has(day)?"checked":"";return `<label class="timepoint-choice ${required?"required":""}"><input type="checkbox" data-day="${esc(day)}" ${checked}><span>${esc(day)}${required?" · 必选":""}</span><small>${item.group_count||0}组</small></label>`}).join("");$("endpointNote").hidden=false;updateEndpoint();picker.querySelectorAll("input").forEach(input=>input.addEventListener("change",updateEndpoint));$("queueButton").disabled=!value.selection_valid}
function selectedDays(){return [...$("timepointPicker").querySelectorAll("input:checked")].map(input=>input.dataset.day)}
function updateEndpoint(){const selected=selectedDays();const options=analysis?.timepoint_options||[];const later=options.filter(item=>selected.includes(item.day_label)&&Number(item.day_number)>=7).sort((a,b)=>Number(a.day_number)-Number(b.day_number));const missing=["Day0","Day1","Day2"].filter(day=>!selected.includes(day));const valid=!missing.length&&later.length;$("endpointNote").textContent=valid?`末点：${later[later.length-1].day_label}（默认使用最后勾选的后期时间点做生长快速排除）`:`当前不能加入队列：${missing.length?`缺少 ${missing.join("、")}；`:"至少选择一个 Day7 或更晚时间点；"}`;$("queueButton").disabled=!valid}
$("refreshButton").addEventListener("click",load);$("newTaskButton").addEventListener("click",()=>{$("taskDialog").showModal();analysis=null;$("queueButton").disabled=true;$("timepointPicker").hidden=true;$("endpointNote").hidden=true;$("analysisResult").textContent="选择文件夹后点击解析。"});$("browseButton").addEventListener("click",async()=>{const result=await api("/api/project/browse-folder",{method:"POST"});if(result.path){$("folderPath").value=result.path}});$("analyzeButton").addEventListener("click",async()=>{try{renderAnalysis(await api("/api/project/analyze-folder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:$("folderPath").value.trim()})}))}catch(error){$("analysisResult").textContent=`解析失败：${error.message}`;$("queueButton").disabled=true}});$("queueButton").addEventListener("click",async()=>{try{const task=await api("/api/project/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("taskName").value.trim(),path:$("folderPath").value.trim(),selected_timepoint_labels:selectedDays()})});$("taskDialog").close();toast(`已加入任务队列：${task.name}，末点 ${task.endpoint_day_label}`);await loadTasks()}catch(error){toast(`加入队列失败：${error.message}`)}});load();
